/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RecruiterSettingsRouteImport } from './routes/recruiter.settings'
import { Route as RecruiterReportsRouteImport } from './routes/recruiter.reports'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter.jobs'
import { Route as RecruiterEvaluationsRouteImport } from './routes/recruiter.evaluations'
import { Route as RecruiterCandidatesRouteImport } from './routes/recruiter.candidates'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter.analytics'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as RecruiterJobsIndexRouteImport } from './routes/recruiter.jobs.index'
import { Route as RecruiterEvaluationsIndexRouteImport } from './routes/recruiter.evaluations.index'
import { Route as RecruiterCandidatesIndexRouteImport } from './routes/recruiter.candidates.index'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as RecruiterJobsNewRouteImport } from './routes/recruiter.jobs.new'
import { Route as RecruiterEvaluationsNewRouteImport } from './routes/recruiter.evaluations.new'
import { Route as RecruiterEvaluationsIdRouteImport } from './routes/recruiter.evaluations.$id'
import { Route as RecruiterCandidatesIdRouteImport } from './routes/recruiter.candidates.$id'
import { Route as AppReportsIdRouteImport } from './routes/app.reports.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RecruiterSettingsRoute = RecruiterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterReportsRoute = RecruiterReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterEvaluationsRoute = RecruiterEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidatesRoute = RecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RecruiterRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const RecruiterJobsIndexRoute = RecruiterJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterJobsRoute,
} as any)
const RecruiterEvaluationsIndexRoute =
  RecruiterEvaluationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RecruiterEvaluationsRoute,
  } as any)
const RecruiterCandidatesIndexRoute =
  RecruiterCandidatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RecruiterCandidatesRoute,
  } as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const RecruiterJobsNewRoute = RecruiterJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecruiterJobsRoute,
} as any)
const RecruiterEvaluationsNewRoute = RecruiterEvaluationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecruiterEvaluationsRoute,
} as any)
const RecruiterEvaluationsIdRoute = RecruiterEvaluationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecruiterEvaluationsRoute,
} as any)
const RecruiterCandidatesIdRoute = RecruiterCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecruiterCandidatesRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRouteWithChildren
  '/recruiter/evaluations': typeof RecruiterEvaluationsRouteWithChildren
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/app/': typeof AppIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/app/reports/$id': typeof AppReportsIdRoute
  '/recruiter/candidates/$id': typeof RecruiterCandidatesIdRoute
  '/recruiter/evaluations/$id': typeof RecruiterEvaluationsIdRoute
  '/recruiter/evaluations/new': typeof RecruiterEvaluationsNewRoute
  '/recruiter/jobs/new': typeof RecruiterJobsNewRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/recruiter/candidates/': typeof RecruiterCandidatesIndexRoute
  '/recruiter/evaluations/': typeof RecruiterEvaluationsIndexRoute
  '/recruiter/jobs/': typeof RecruiterJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/app': typeof AppIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/app/reports/$id': typeof AppReportsIdRoute
  '/recruiter/candidates/$id': typeof RecruiterCandidatesIdRoute
  '/recruiter/evaluations/$id': typeof RecruiterEvaluationsIdRoute
  '/recruiter/evaluations/new': typeof RecruiterEvaluationsNewRoute
  '/recruiter/jobs/new': typeof RecruiterJobsNewRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/recruiter/candidates': typeof RecruiterCandidatesIndexRoute
  '/recruiter/evaluations': typeof RecruiterEvaluationsIndexRoute
  '/recruiter/jobs': typeof RecruiterJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRouteWithChildren
  '/recruiter/evaluations': typeof RecruiterEvaluationsRouteWithChildren
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/reports': typeof RecruiterReportsRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/app/': typeof AppIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/app/reports/$id': typeof AppReportsIdRoute
  '/recruiter/candidates/$id': typeof RecruiterCandidatesIdRoute
  '/recruiter/evaluations/$id': typeof RecruiterEvaluationsIdRoute
  '/recruiter/evaluations/new': typeof RecruiterEvaluationsNewRoute
  '/recruiter/jobs/new': typeof RecruiterJobsNewRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/recruiter/candidates/': typeof RecruiterCandidatesIndexRoute
  '/recruiter/evaluations/': typeof RecruiterEvaluationsIndexRoute
  '/recruiter/jobs/': typeof RecruiterJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/recruiter'
    | '/register'
    | '/app/history'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/upload'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/evaluations'
    | '/recruiter/jobs'
    | '/recruiter/reports'
    | '/recruiter/settings'
    | '/app/'
    | '/recruiter/'
    | '/app/reports/$id'
    | '/recruiter/candidates/$id'
    | '/recruiter/evaluations/$id'
    | '/recruiter/evaluations/new'
    | '/recruiter/jobs/new'
    | '/app/reports/'
    | '/recruiter/candidates/'
    | '/recruiter/evaluations/'
    | '/recruiter/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/app/history'
    | '/app/profile'
    | '/app/settings'
    | '/app/upload'
    | '/recruiter/analytics'
    | '/recruiter/reports'
    | '/recruiter/settings'
    | '/app'
    | '/recruiter'
    | '/app/reports/$id'
    | '/recruiter/candidates/$id'
    | '/recruiter/evaluations/$id'
    | '/recruiter/evaluations/new'
    | '/recruiter/jobs/new'
    | '/app/reports'
    | '/recruiter/candidates'
    | '/recruiter/evaluations'
    | '/recruiter/jobs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/recruiter'
    | '/register'
    | '/app/history'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/upload'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/evaluations'
    | '/recruiter/jobs'
    | '/recruiter/reports'
    | '/recruiter/settings'
    | '/app/'
    | '/recruiter/'
    | '/app/reports/$id'
    | '/recruiter/candidates/$id'
    | '/recruiter/evaluations/$id'
    | '/recruiter/evaluations/new'
    | '/recruiter/jobs/new'
    | '/app/reports/'
    | '/recruiter/candidates/'
    | '/recruiter/evaluations/'
    | '/recruiter/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RecruiterRoute: typeof RecruiterRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/recruiter/settings': {
      id: '/recruiter/settings'
      path: '/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof RecruiterSettingsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/reports': {
      id: '/recruiter/reports'
      path: '/reports'
      fullPath: '/recruiter/reports'
      preLoaderRoute: typeof RecruiterReportsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/evaluations': {
      id: '/recruiter/evaluations'
      path: '/evaluations'
      fullPath: '/recruiter/evaluations'
      preLoaderRoute: typeof RecruiterEvaluationsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidates': {
      id: '/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof RecruiterCandidatesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/recruiter/jobs/': {
      id: '/recruiter/jobs/'
      path: '/'
      fullPath: '/recruiter/jobs/'
      preLoaderRoute: typeof RecruiterJobsIndexRouteImport
      parentRoute: typeof RecruiterJobsRoute
    }
    '/recruiter/evaluations/': {
      id: '/recruiter/evaluations/'
      path: '/'
      fullPath: '/recruiter/evaluations/'
      preLoaderRoute: typeof RecruiterEvaluationsIndexRouteImport
      parentRoute: typeof RecruiterEvaluationsRoute
    }
    '/recruiter/candidates/': {
      id: '/recruiter/candidates/'
      path: '/'
      fullPath: '/recruiter/candidates/'
      preLoaderRoute: typeof RecruiterCandidatesIndexRouteImport
      parentRoute: typeof RecruiterCandidatesRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/recruiter/jobs/new': {
      id: '/recruiter/jobs/new'
      path: '/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof RecruiterJobsNewRouteImport
      parentRoute: typeof RecruiterJobsRoute
    }
    '/recruiter/evaluations/new': {
      id: '/recruiter/evaluations/new'
      path: '/new'
      fullPath: '/recruiter/evaluations/new'
      preLoaderRoute: typeof RecruiterEvaluationsNewRouteImport
      parentRoute: typeof RecruiterEvaluationsRoute
    }
    '/recruiter/evaluations/$id': {
      id: '/recruiter/evaluations/$id'
      path: '/$id'
      fullPath: '/recruiter/evaluations/$id'
      preLoaderRoute: typeof RecruiterEvaluationsIdRouteImport
      parentRoute: typeof RecruiterEvaluationsRoute
    }
    '/recruiter/candidates/$id': {
      id: '/recruiter/candidates/$id'
      path: '/$id'
      fullPath: '/recruiter/candidates/$id'
      preLoaderRoute: typeof RecruiterCandidatesIdRouteImport
      parentRoute: typeof RecruiterCandidatesRoute
    }
    '/app/reports/$id': {
      id: '/app/reports/$id'
      path: '/$id'
      fullPath: '/app/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsIdRoute: typeof AppReportsIdRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIdRoute: AppReportsIdRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RecruiterCandidatesRouteChildren {
  RecruiterCandidatesIdRoute: typeof RecruiterCandidatesIdRoute
  RecruiterCandidatesIndexRoute: typeof RecruiterCandidatesIndexRoute
}

const RecruiterCandidatesRouteChildren: RecruiterCandidatesRouteChildren = {
  RecruiterCandidatesIdRoute: RecruiterCandidatesIdRoute,
  RecruiterCandidatesIndexRoute: RecruiterCandidatesIndexRoute,
}

const RecruiterCandidatesRouteWithChildren =
  RecruiterCandidatesRoute._addFileChildren(RecruiterCandidatesRouteChildren)

interface RecruiterEvaluationsRouteChildren {
  RecruiterEvaluationsIdRoute: typeof RecruiterEvaluationsIdRoute
  RecruiterEvaluationsNewRoute: typeof RecruiterEvaluationsNewRoute
  RecruiterEvaluationsIndexRoute: typeof RecruiterEvaluationsIndexRoute
}

const RecruiterEvaluationsRouteChildren: RecruiterEvaluationsRouteChildren = {
  RecruiterEvaluationsIdRoute: RecruiterEvaluationsIdRoute,
  RecruiterEvaluationsNewRoute: RecruiterEvaluationsNewRoute,
  RecruiterEvaluationsIndexRoute: RecruiterEvaluationsIndexRoute,
}

const RecruiterEvaluationsRouteWithChildren =
  RecruiterEvaluationsRoute._addFileChildren(RecruiterEvaluationsRouteChildren)

interface RecruiterJobsRouteChildren {
  RecruiterJobsNewRoute: typeof RecruiterJobsNewRoute
  RecruiterJobsIndexRoute: typeof RecruiterJobsIndexRoute
}

const RecruiterJobsRouteChildren: RecruiterJobsRouteChildren = {
  RecruiterJobsNewRoute: RecruiterJobsNewRoute,
  RecruiterJobsIndexRoute: RecruiterJobsIndexRoute,
}

const RecruiterJobsRouteWithChildren = RecruiterJobsRoute._addFileChildren(
  RecruiterJobsRouteChildren,
)

interface RecruiterRouteChildren {
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterCandidatesRoute: typeof RecruiterCandidatesRouteWithChildren
  RecruiterEvaluationsRoute: typeof RecruiterEvaluationsRouteWithChildren
  RecruiterJobsRoute: typeof RecruiterJobsRouteWithChildren
  RecruiterReportsRoute: typeof RecruiterReportsRoute
  RecruiterSettingsRoute: typeof RecruiterSettingsRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterCandidatesRoute: RecruiterCandidatesRouteWithChildren,
  RecruiterEvaluationsRoute: RecruiterEvaluationsRouteWithChildren,
  RecruiterJobsRoute: RecruiterJobsRouteWithChildren,
  RecruiterReportsRoute: RecruiterReportsRoute,
  RecruiterSettingsRoute: RecruiterSettingsRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RecruiterRoute: RecruiterRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
