# Generated by Django 5.2.16 on 2026-07-14 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ats_score', models.IntegerField(default=0)),
                ('quality_score', models.IntegerField(default=0)),
                ('extracted_skills', models.JSONField(default=list)),
                ('extracted_experience', models.JSONField(default=list)),
                ('extracted_education', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resumes.resume')),
            ],
            options={
                'db_table': 'analyses',
                'indexes': [models.Index(fields=['resume'], name='idx_analyses_resume')],
            },
        ),
    ]
